site_name: MkFibre
site_url: https://ncolombelli.github.io/
nav:
    - Home: index.md
    - About: about.md
    - Orange: orange.md
theme: 
    name: mkdocs # readthedocs # windmill # readthedocs bootstrap4
    palette: teal #indigo pink black purpple teal blue light blue green yellow