site_name: MkFibre
site_url: https://ncolombelli.github.io/
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs # windmill # readthedocs bootstrap4
    - Serie: about.md
theme: readthedocs # windmill # readthedocs bootstrap4