site_name: La fibre optique
site_url: https://ncolombelli.github.io/
nav:
    - Home: index.md
    - Orange: orange.md
    - AIC: aic.md
theme: 
    name: readthedocs # mkdocs # windmill # readthedocs # bootstrap4 # Third Party Themes
    palette: 
        primary: teal #indigo pink black purpple teal blue light blue green yellow
        accent: teal